output_dir: tracking_result/tracking_hetero

model_name_on_wandb: tracking-gnn-fixcluster

trainer:
    name: gnn_sparse

data:
    name: hetero_hitgraphs_sparse
    input_dir: # trigger input dir
    input_dir2: # nontrigger input dir
    n_train: 50000
    n_valid: 50000
    real_weight: 1
    batch_size: 32
    n_workers: 8
    n_folders: 2

model:
    name: hetero_gnn
    input_dim: 5
    hidden_dim: 128
    hidden_activation: Tanh
    n_graph_iters: 8
    layer_norm: True
    loss_func: binary_cross_entropy

optimizer:
    name: Adam
    learning_rate: 0.0001
    weight_decay: 1.e-4
    lr_decay_schedule:
        - {start_epoch: 60, end_epoch: 128, factor: 0.1}

training:
    n_total_epochs: 128
