output_dir: train_results/biatt-blri/
wandb:
  project_name: physics-trigger
  run_name: biatt-blri
  tags: ["biatt", "blri", "loopy", "layernorm", "batchnorm", "prelu"]

loss: 
  sigma: 1
  beta: 0.00761802068354479
  mse_weight: 0.001
  #beta: 10

epochs: 1
finetune_epochs: 10
optimizer:
  finetune_factor: 0.00000000165554383046
  type: Adam
  learning_rate: 0.00008014451108346615
  beta_1: 0.7650424449768395
  beta_2: 0.999
  eps: 0.00003891674021588362
  weight_decay: 0.00001892968038142768
  learning_rate_decay_rate: 0.00008014451108346615

model_mod: 1
model:
  num_features: 32
  layers_spec: [[128, 8], [128, 8], [128, 8], [128, 8], [128, 8], [128, 8]]
  ln: True
  bn: False
  num_classes: 2
  aggregator_activation: softmax
  recalculate_hits_mean: True
  self_split: False
  hidden_activation: PReLU
  use_cholesky: True
  normalize_features: True
  normalization_rescale: 1000

data:
        name: gt-trkvec-masked
        trigger_input_dir: # Trigger input data here
        nontrigger_input_dir: # Non trigger input data here
        rescale_by_percentile: 14

        n_train: 500000
        n_valid: 10000 #0
        n_test: 1000 #00
        batch_size: 512

        add_geo_features: True
        use_radius: True
        use_predicted_pz: True
        use_energy: False
        use_momentum: False
        use_center: True
        use_parallel_momentum: False

        use_physics_pred: False

        n_workers: 16
        load_complete_graph: False
